server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:greenwave}
    username: ${DB_USERNAME:greenwave_user}
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:GreenWaveSuperSecretKeyForDevelopmentOnly123456789}
  expiration-ms: 86400000